* build-aux/version.c: Added tool to plumb svn revision into the code.  * build-aux/Makefile.am: Added to build build-aux/version.  * src/Makefile.am: Added rules to generate src/version.h from build-aux/version.  * Makefile.am: Updated dist-hook to check for modfied/mixed/switched working copies.  * configure.ac: Updated.
git-svn-id: https://htpmt.googlecode.com/svn/trunk@71 25275c40-b298-11de-9c04-c7668166297d

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,10 +1,23 @@
-SUBDIRS = contrib libmd src doc man tests
+SUBDIRS = build-aux contrib libmd src doc man tests
 MAINTAINERCLEANFILES = aclocal.m4 configure config.h.in Makefile.in $(distdir).tar.gz $(distdir).tar.bz2
 
-# Create ChangeLog on the fly during 'make dist'
 dist-hook:
-	$(srcdir)/build-aux/missing --run svn info $(abs_srcdir) \
-	    	>/dev/null 2>&1 \
-	       	&& $(srcdir)/build-aux/missing --run svn log -g $(abs_srcdir) \
-	       	| $(srcdir)/contrib/gnuify-changelog  > $(distdir)/ChangeLog \
-		|| exit 0
+	@if svn info $(abs_srcdir) >/dev/null 2>&1; then \
+		svnversion=`svnversion $(abs_srcdir)`; \
+		if echo $${svnversion} | grep --silent ":"; then \
+			echo "Error: cannot make dist from a mixed-revision working copy: $${svnversion}"; \
+			exit 1; \
+		fi; \
+		if echo $${svnversion}  | grep --silent "M"; then \
+			echo "Error: cannot make dist from a modified working copy: $${svnversion}"; \
+			exit 1; \
+		fi; \
+		if echo $${svnversion}  | grep --silent "S"; then \
+			echo "Error: cannot make dist from a switched working copy: $${svnversion}"; \
+			exit 1; \
+		fi; \
+		/usr/bin/env echo -n "Populating ChangeLog... "; \
+	       	svn log -g $(abs_srcdir) \
+	       	| $(srcdir)/contrib/gnuify-changelog  > $(distdir)/ChangeLog ; \
+		echo Done; \
+	fi
