* Merged trunk:r70-71  * Added svn:keywords property on everything.
git-svn-id: https://htpmt.googlecode.com/svn/branches/releases/1.0@73 25275c40-b298-11de-9c04-c7668166297d

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,8 +1,25 @@
 #ACLOCAL_AMFLAGS = -I m4
-SUBDIRS = contrib libmd src doc man tests
+SUBDIRS = build-aux contrib libmd src doc man tests
 MAINTAINERCLEANFILES = aclocal.m4 configure config.h.in Makefile.in en@quot.po en@boldquot.po version_info.h
 EXTRA_DIST = TODO BUGS
 
-# Create ChangeLog on the fly during 'make dist'
 dist-hook:
-	test -z `svn info ${abs_srcdir}` || $(srcdir)/build-aux/missing --run svn log ${abs_srcdir} | ${srcdir}/contrib/gnuify-changelog  > ${distdir}/ChangeLog
+	@if svn info $(abs_srcdir) >/dev/null 2>&1; then \
+		svnversion=`svnversion $(abs_srcdir)`; \
+		if echo $${svnversion} | grep --silent ":"; then \
+			echo "Error: cannot make dist from a mixed-revision working copy: $${svnversion}"; \
+			exit 1; \
+		fi; \
+		if echo $${svnversion}  | grep --silent "M"; then \
+			echo "Error: cannot make dist from a modified working copy: $${svnversion}"; \
+			exit 1; \
+		fi; \
+		if echo $${svnversion}  | grep --silent "S"; then \
+			echo "Error: cannot make dist from a switched working copy: $${svnversion}"; \
+			exit 1; \
+		fi; \
+		/usr/bin/env echo -n "Populating ChangeLog... "; \
+	       	svn log -g $(abs_srcdir) \
+	       	| $(srcdir)/contrib/gnuify-changelog  > $(distdir)/ChangeLog ; \
+		echo Done; \
+	fi
